version: "3"

services:

  api:
    container_name: kaleydodoc_api
    image: kaleydodoc_api
    build:
      context: ./
      dockerfile: "docker/api/Dockerfile"
    ports:
      - "8000:8000"
    volumes:
      - ./files:/files
      - ./data:/data
    restart: always
