version: "3.9"

services:

  api:
    container_name: kaleydodoc_api
    image: kaleydodoc_api
    build:
      context: ./
      dockerfile: "Docker/api/Dockerfile"
    ports:
      - "6666:6666"
    volumes:
      - ./files:/files
      - ./data:/data
      - ./src:/src
    restart: always
